version: '2'
services:
  service:
    container_name: rastrojs
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./dist:/opt/services/rastrojs/dist
      - ./node_modules:/opt/services/rastrojs/node_modules
    image: my_tag/rastrojs
    tty: true
    environment:
      - NODE_ENV=production
    entrypoint: node dist/app.js